# 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

**비동기 함수**란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말한다. 비동기 함수를 호출하면 비동기로 동작하는 **코드가 완료되지 않아도 기다리지 않고 즉시 종료**된다. 즉, 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

```jsx
let todos;

// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프의 변수에 할당한다.
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 post를 취득
get("https://jsonplaceholder.typicode.com/posts/1");
console.log(todos); // ② undefined
```

위 코드의 `console.log(todos)`의 결과는 **undefined**로 원하는 결과가 나오지 않는다.

비동기 함수 get이 호출되면 함수 코드를 평가하는 과정에서 **get 함수의 실행 컨텍스트가 생성**되고 **콜 스택에 푸시**된다. 이후 실행 과정에서 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.

**get 함수가 종료하면 콜스택에서 팝** 되고, 2번의 console.log가 호출된다. 만약 **console.log가 호출되기 직전에 load 이벤트가 발생해도 console.log보다 먼저 실행되지 않는다.**

서버로부터 응답이 도착하면 xhr 객체에서 load 이벤트가 발생한다. xhr.onload 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되는 것이 아니다. 일단 **태스크 큐에 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행**된다.

콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또 다시 비동기 함수를 호출해야 한다면 이를 **콜백 헬**이라 한다.

```jsx
get("/step1", (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      get(`/step4/${c}`, (d) => {
        console.log(d);
      });
    });
  });
});
```

### 45.1.2 에러 처리의 한계

콜백 패턴의 문제점 중 가장 심각한 것은 **에러 처리가 곤란하다는 것**이다.

```jsx
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error("캐치한 에러", e);
}
```

- try … catch … finally 문
  - 에러 처리를 구현하는 방법이다. **먼저 try 코드 블록이 실행**된다. 실행중 에러가 발생하면 catch문의 err 변수에 전달되고 catch 코드 블럭이 실행된다. finally 코드 블록은 에러 발생과 상관없이 반드시 한 번 실행된다.

위 코드에서 에러는 **catch 코드 블록에서 캐치되지 않는다.**

setTimeout 함수는 1초후에 콜백 함수가 실행되도록 타이머를 설정하고, 이후 콜백 함수는 에러를 발생시킨다. 하지만 이 에**러는 catch 코드 블록에서 캐치되지 않는다.**

**setTimeout은** 비동기 함수이므로 **콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료**되어 콜 스택에서 제거된다. **타이머가 만료되고 콜백 함수가 태스크 큐로 푸시**된다. 콜 스택이 비어있으면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.

**setTimout 콜백 함수가 실행될 때 이미 setTimeout 함수는 콜 스택에서 제거된 상태**다. 이것은 setTImeout 함수의 **콜백 함수를 호출한 것이 setTimeout 이 아니라는 것을 의미**한다.

**에러는 호출자 방향으로 전파**된다. 즉, 콜 **스택의 아래 방향으로 전**파된다.

위의 콜백 헬이랑 에러 처리의 **문제를 해결하기 위해 프로미스**가 도입되었다.

---

# 45.2 프로미스의 생성

**Promise** 생성자 함수를 new 연산자와 함께 호출하면 프로미스를 생성한다.

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 함수는 **resolve**와 **reject**를 인수로 전달받는다.

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
  if (/* 비동기 처리 성공 */) {
    resolve('result');
  } else { /* 비동기 처리 실패 */
    reject('failure reason');
  }
});
```

비동기 처리가 완료되면 resolve를 호춣하고, 실패하면 reject 함수를 호출한다. 이를 이용해 앞에 살펴본 get을 다시 구현해 보자.

```jsx
// GET 요청을 위한 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출한다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```

프로미스는 아래와 같이 현재 비동기 상태 정보를 갖는다.

| 프로미스 상태 정보 | 의미                                  | 상태 변경 조건                   |
| ------------------ | ------------------------------------- | -------------------------------- |
| **pending**        | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| **fulfuiied**      | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| **rejected**       | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

프로미스는 기본적으로 pending 상태이고, 비동기 처리가 완료되면 프로미스 상태가 변경된다.

- 비동기 처리 **성공** : **reslove** 함수 호출하고, **fulfilled** 상태
- 비동기 처리 **실패** : **reject** 함수 호출하고, **rejected** 상태

---

# 45.3 프로미스의 후속 처리 메서드

비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야한다. 프로미스는 후속 메서드 then, catch, finally를 제공한다. 후속 메서드의 콜백 함수에 프로미스의 처리 결과가 전달된다.

**모든 후속 처리 메서드는 프로미스를 반환하며 비동기로 동작한다.**

### 45.3.1 Promise.prototype.then

then 메서드는 두 개의 콜백 함수를 인수로 전달받는다.

- 첫 번째, 프로미스가 **fulfilled 상태가 되면 호출**, 이때 콜백 함수는 프로미스의 처리 결과를 인수로 받는다
- 두 번째, **rejected 상태가 되면 호출**, 콜백 함수는 프로미스의 에러를 인수로 전달받는다.

then 메서드는 **언제나 프로미스를 반환**한다. then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 프로미스가 아닌 값을 반환하면 암묵적으로 resolve 또는 reject를 한다.

### 45.3.2 Promise.prototype.catch

**catch** 메서든느 하나의 콜백 함수를 인수로 받는다. catch 메서드는 프로미스가 **rejected 상태인 경우만 호출된다.**

**catch**는 then(undefined, onRejected)와 동일하게 동작한다. 따라서 then 메서드와 마찬가지로 **언제나 프로미스를 반환한다.**

### 45.3.3 Promise.prototype.finally

finally 메서드는 성공 실패 상관없이 무조건 한 번 호출된다.

---

# 45.4 프로미스의 에러 처리

프로미스는 then 메서드나 catch 메서드를 사용하여 에러처리 할 수 있다.

---

# 45.5 프로미스 체이닝

콜백 헬 문제를 프로미스는 then, catch, finally 후속 처리 메서드를 통해 콜백 헬을 해결한다.

```jsx
const url = "https://jsonplaceholder.typicode.com";

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 취득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

**후속 메서드는 언제나 프로미스를 반환**하므로 **연속적으로 호출**할 수 있다. 이를 **프로미스 체이닝**이라고 한다.

---

# 45.6 프로미스의 정적 메서드

### 45.6.1 Promise.resolve/ Promise.reject

두 메서드는 **이미 존재하는 값을 래핑하여 프로미스를 생성**하기 위해 사용한다.

Promise.resolve는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]
```

### 45.6.2 Promise.all

여러 개의 비동기 처리를 **모두 병렬 처리할 떄 사용**한다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] ⇒ 약 6초 소요
  })
  .catch(console.error);
```

세게의 비동기 함수가 순차적으로 실행되므로 6초 경과

Promise.all 메서드는 여러개의 비동기 처리를 모두 병렬로 처리할 때 사용

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error);
```

Promise.all 메서드는 **프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달**받는다. 그리고 전달받은 **모든 프로미스가 fulfilled 상태**가 되면 결과를 뱅려에 저장해 **새로운 프로미스를 반환**한다. 해당 함수는 **프로미스의 처리 순서가 보장**된다.

**하나의 프로미스라도 rejected 상태가 되면 나머지 프로미스는 기다리지 않고 즉시 종료**된다.

```jsx
Promise.all([
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 1")), 3000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 2")), 2000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 3")), 1000)
  ),
])
  .then(console.log)
  .catch(console.log); // Error: Error 3
```

### 45.6.3 Promise.race

해당 메서드는 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 게 아니라, **가장 먼저 fulfilled 된 상태의 결과를 리턴**한다.

### 45.6.4 Prmose.allSettled

해당 메서드는 모든 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다. 그리고 **전부 setteld 상태( fulfilled 또는 rejected 상태 ) 되면 처리 결과를 배열로 반환**한다.

---

# 45.7 마이크로태스크 큐

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

1→2→3 순으로 출력될 것처럼 보이지만 2 → 3 → 1 순으로 출력된다. 그 이유는 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 **마이크로태스크 큐**에 저장되기 때문이다.

마이크로태스크 큐는 **프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장**된다. 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.

마이크로태스크 큐는 태스크 큐보다 우선순위가 높다. 즉 , 이벤트 루프는 콜 스택이 비면 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다. 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

---

# 45.8 fetch

fetch 함수는 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.

fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>
  console.log(response)
);
```

**fetch 함수**는 HTTP 응답을 나타내는 **Response 객체를 래핑한 프로미스를 반환**하므로 후속 처리 메서드 then을 통해 프로미스가 reslove한 Response 객체를 전달받을 수 있다. Resopnse 객체는 HTTP 응답을 나타내는 다양한 프로퍼티를 제공한다.

fetch 함수를 사용할 때는 에러 처리에 주의해야 한다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  .then(() => console.log("ok"))
  .catch(() => console.log("error"));
```

위 예제에서 catch 메서드에 의해 “error”가 출력될 것처럼 보이지만 “ok”가 출력된다.

**fetch 함수가 반환하는 프로미스는 404, 500과 같은 HTTP 에러가 발생해도 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다. 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject한다.**

따라서 fetch 함수를 사용할 때는 ok 상태를 확인하여 명시적으로 에러를 처리할 필요가 있다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  // response는 HTTP 응답을 나타내는 Response 객체다.
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.error(err));
```

참고로 axios는 모든 HTTP 에러를 reject하는 프로미스를 반환한다.
